### PR TITLE
Unique hash IDs for all persons in the CCJ system

### PR DESCRIPTION
**Pull request by bepetersn**
Herein I've implemented a hash based on an inmate's name, birthdate, race, and gender to create a unique identifer for persons who enter the CCJ system, outside of their status as inmates for particular stays in that system. This is known as `person_id` for now. The expectation is that over time we will begin to see the phenomenon of recidivism, or people returning to jail, which we are currently blind to. This hash value is the new primary key for our inmate object, while almost all of the fields previously associated with our inmate object, including `jail_id`, are now associated with a particular `JailStay` object, with the exceptions of gender and race.

You can access a list of `JailStay` objects associated with a particular inmate by calling `inmate.jail_history.all()`, get just the latest one with `inmate.jail_history.all()[0]`, or search all inmate objects with `CountyInmate.filter(jail_history__<field>=<value)`. 

I don't THINK I've broken anything with this code. (please, pull from my remote and test it out before letting me mess up our production server!) Much credit to Norbert's earlier decoupling of our code via inmate_details and inmate_utils on that count. Also credit to Wil and probably Dave for how charges_history and housing_history are set up, as I used these as a guide.

And now we just need to add this to our API... I am working on it.

### CODE REVIEW

**Comment by bepetersn** [comment]
I was just reviewing our code base, looking for things I might possibly break with this code. I think I've fixed a few, but there are still several scripts that need updating / working around. I'd love it if any one would point out anything I've missed.

**Comment by nwinklareth** [comment]
Brian,

I like the idea you and David worked out and I like how you implement it and I recommend that this be added to the 2.0 version of the API and not the 1.0 version, for the following reasons:
- more normalization of the data models is needed
- extract person info to Person model, including unique hash id, although use SHA1, less collisions than MD5
- for partial collision resolution we need to store name and birth information
- to improve collision resolution even further an attendee of last night's Django Jail Hack, suggested that by storing the photo we could use photo comparison, human or programmatically, to distinguish between the two identities
- another attendee pointed out that we can even go further and when we detect an individual has left the Jail System by examining the State website and using the personal info we can determine if the individual was convicted, so we could add conviction info
- given the above changes and observations you and David made CountyInmate model should become JailStay model
- finally given the large holes in our current data set resetting the data start point should be reset to a more recent point

Also introducing the 2.0AP and new data set would not mean eliminating the 1.0 API and associated data set. It would continue to function serving the data collected, that data set would not be being updated.

Thoughts?

**Comment by fgregg** [comment]
When we first started talking about this project, we decided not store
personally identifying information. This pull request does that, but
storing the name, birthdate, and photo for collision resolution does not.

If we are really worried with has collision, we can just increase the hash
length.

On Thu, Aug 15, 2013 at 8:33 AM, nwinklareth notifications@github.comwrote:

> Brian,
> 
> I like the idea you and David worked out and I like how you implement it
> and I recommend that this be added to the 2.0 version of the API and not
> the 1.0 version, for the following reasons:
> - more normalization of the data models is needed
> - extract person info to Person model, including unique hash id,
>   although use SHA1, less collisions than MD5
> - for partial collision resolution we need to store name and birth
>   information
> - to improve collision resolution even further an attendee of last
>   night's Django Jail Hack, suggested that by storing the photo we could use
>   photo comparison, human or programmatically, to distinguish between the two
>   identities
> - another attendee pointed out that we can even go further and when we
>   detect an individual has left the Jail System by examining the State
>   website and using the personal info we can determine if the individual was
>   convicted, so we could add conviction info
> - given the above changes and observations you and David made
>   CountyInmate model should become JailStay model
> - finally given the large holes in our current data set resetting the
>   data start point should be reset to a more recent point
> 
> Also introducing the 2.0AP and new data set would not mean eliminating the
> 1.0 API and associated data set. It would continue to function serving the
> data collected, that data set would not be being updated.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/117#issuecomment-22702928
> .

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by eads** [comment]
+1 to not keeping more information than we need. I'd really rather not store birthdates and instead live with the possibility of collisions.

**Comment by bepetersn** [comment]
Thanks for your comments and suggestions, Norbert. In regards to your
points:
- What more "normalization of the data models" is needed?
- In terms of full collisions, it seems that we'll be safely tracking billions of people (hope not) before the MD5 hashing function itself is likely to give a collision, since it uses 128-bits, and our data is only a string of 20-30ish characters. However, perhaps a partial collision really would be a bad thing? I guess if one of our 32 digit hexadecimal strings can be equivalent to another, then that would be bad, and effectively equivalent to a collision in our system. It's hard for me to understand the relationships between these things, even after googling around. Care to wax eloquent? In the worst case we could, as Gregg suggested, use SHA-256 or something like that.
- With this pull request, I effectively HAVE turned the CountyInmate model into the Person model. The JailStay model is already there. I was just holding off on changing the many references to the CountyInmate name, since no one has really confirmed that they approve of this whole change up to now.
- Finally, what exactly would an API 2.0 mean? Are you talking about maintaining multiple levels of our API? 

EDIT: Ah, upon closer reading of what you wrote, I see that you have suggested to stop updating API v1.0, but reset our data for a new API 2.0. This sounds... feasible.

**Comment by bepetersn** [comment]
Also, we can analyze the picture of an inmate at scrape-time, like name and birthdate, and then include some simplified analysis of it in our hash. That's probably within reach; however, it's also likely to cause more collisions, since any encoding of a picture will be a lot of bytes--at least that's my understanding.

Note that the longer we wait to implement a change like this, the more names and birthdates we can never retrieve and hash, and the longer it will take before any returning inmates can be observed.

**Comment by bepetersn** [comment]
Well, it looks like these changes might be a little too much to get done right now, through a pull request, without first discussing. Maybe at the next hack we can work out what we want to do.

**Pull request closed without merging**
