### PR TITLE
Replace DOB with AGE in countyapi/models.py

### PR DESCRIPTION
**Pull request by fgregg**
Replace identifying date of birth with age at booking.

### CODE REVIEW

**Comment by eads** [comment]
DOB isn't very identifying without name, though, is it?

On Thu, Dec 6, 2012 at 9:32 AM, Forest Gregg notifications@github.comwrote:

> ## Replace identifying date of birth with age at booking.
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/fgregg/cookcountyjail patch-1
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/sc3/cookcountyjail/pull/15
> Commit Summary
> - Update countyapi/models.py
> 
> File Changes
> - _M_ countyapi/models.py (2)
> 
> Patch Links
> - https://github.com/sc3/cookcountyjail/pull/15.patch
> - https://github.com/sc3/cookcountyjail/pull/15.diff
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/15.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by fgregg** [comment]
DOB has a lots of bits of information. http://en.wikipedia.org/wiki/Differential_privacy#Motivation 

Is there a use case for DOB other than calculating the age. If not, then why not just do it when we collect the data?

**Comment by eads** [comment]
My concern is mainly keeping the data as close to the source as possible
for as long as possible, which is a philosophy I've learned to appreciate
more in my short time at the Tribune. But we can do it this way. Can you
write a ticket for our crew so whoever decides to tackle these fields in
the scraper (probably Wilberto) knows to calculate age from dob?

On Thu, Dec 6, 2012 at 10:17 AM, Forest Gregg notifications@github.comwrote:

> DOB has a lots of bits of information.
> http://en.wikipedia.org/wiki/Differential_privacy#Motivation
> 
> Is there a use case for DOB other than calculating the age. If not, then
> why not just do it when we collect the data?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/15#issuecomment-11091896.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by fgregg** [comment]
I'm sympathetic to that philosophy. We can perhaps build confidence if
write a test script that can calculate the distribution of current ages (by
finding the diff between DOB and current date) and compares it to the
distribution of ages of current inmates stored in the datastore.

On Thu, Dec 6, 2012 at 10:23 AM, David Eads notifications@github.comwrote:

> My concern is mainly keeping the data as close to the source as possible
> for as long as possible, which is a philosophy I've learned to appreciate
> more in my short time at the Tribune. But we can do it this way. Can you
> write a ticket for our crew so whoever decides to tackle these fields in
> the scraper (probably Wilberto) knows to calculate age from dob?
> 
> On Thu, Dec 6, 2012 at 10:17 AM, Forest Gregg notifications@github.comwrote:
> 
> > DOB has a lots of bits of information.
> > http://en.wikipedia.org/wiki/Differential_privacy#Motivation
> > 
> > Is there a use case for DOB other than calculating the age. If not, then
> > why not just do it when we collect the data?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/pull/15#issuecomment-11091896>.
> 
> ## 
> 
> David Eads - 773.354.2285
> News applications developer, Chicago Tribune (
> http://www.chicagotribune.com/news/data/)
> Founder, FreeGeek Chicago (http://freegeekchicago.org)
> 
> “The awful thing about life is this: everyone has their reasons.” -- Jean
> Renoir
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/15#issuecomment-11092181.

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by codersquid** [comment]
While I realize the privacy concerns involved in persisting this data, I also think you guys should think about what you are discarding when you get rid of DOB and other information. Consider the case where a researcher needs DOB information combined with some other factor in order to determine systemic biases in the population that is being arrested versus the general population of people who are arrested and let go, or some such. And consider the case where our logic for determining age is cacked up and we just corrupted the poor researcher's data set. Or maybe our age logic isn't exactly cacked up but there's something else going on. (if you like, at the next hack meet, I could go through scholarly literature (with some advice on which disciplines to search) to see what type of information scientists typically need. (in my other spare time I think about open science and the tool sets that will be needed by, for example, psychologists who need to persist their data in an open way whilst preserving the privacy of their subjects. I am interested in open science and psychology).

**Comment by fgregg** [comment]
I hear those concerns. It seems like there are two issues.

First, how do we ensure that we are calculating the age correctly. I think
the kind of test script I described should reassure us of that.

Second, there may be some research question where an age measure (years
alive) is not precise enough, and a question requires more precision
(months alive, days alive). The only scholarly research that I've seen that
depends upon that kind of precisions is research into what are called
'birthday effects.' (i.e.
http://www.hks.harvard.edu/pepg/PDF/events/Munich/PEPG-04-24Strom.pdf)

That's neat, but you could also imagine (and indeed research has been
done), on 'name effects' but we have decided not to store names. We need to
think about the tradeoffs between what could be neat to possibly know and
the potential risk to a vulnerable population that has not given consent to
be part of anyone's research project.

I'm not saying that I know exactly where that tradeoff is, but for me DOB
seems to not be useful enough.

-Forest

difference I can think of is in a

  There is some

On Thu, Dec 6, 2012 at 10:57 AM, codersquid notifications@github.comwrote:

> While I realize the privacy concerns involved in persisting this data, I
> also think you guys should think about what you are discarding when you get
> rid of DOB and other information. Consider the case where a researcher
> needs DOB information combined with some other factor in order to determine
> systemic biases in the population that is being arrested versus the general
> population of people who are arrested and let go, or some such. And
> consider the case where our logic for determining age is cacked up and we
> just corrupted the poor researcher's data set. Or maybe our age logic isn't
> exactly cacked up but there's something else going on. (if you like, at the
> next hack meet, I could go through scholarly literature (with some advice
> on which disciplines to search) to see what type of information scientists
> typically need. (in my other spare time I think about open science and the
> tool sets that will be needed by, for example, psychologists who need to
> persist their data in an open way whilst preserving the privacy of their
> subjects. I am interested in open science and psychology).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/15#issuecomment-11093728.

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by eads** [comment]
We could calculate a fractional age to some "fuzzy enough" level of
precision to balance precision and privacy. I'm about 32.6 years old, but
you couldn't use that to determine my exact birthdate.

**Comment by fgregg** [comment]
How about AGE, and then winter, spring, summer, fall

**Comment by eads** [comment]
That seems equivalent to fractional, but now you can't do math on it....

On Thu, Dec 6, 2012 at 11:27 AM, Forest Gregg notifications@github.comwrote:

> How about AGE, and then winter, spring, summer, fall
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/15#issuecomment-11095089.

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

“The awful thing about life is this: everyone has their reasons.” -- Jean
Renoir

**Comment by fgregg** [comment]
I've never seen any research that actually cared about how long someone has
been alive at a precision higher than years. Instead, researchers have been
interested in whether a persons birthday falls before or after some
arbitrary, bureaucratic cutoff. If we use fractional age, then researchers
will likely try to get a birth date range out of it. Might as well give
that range directly.

As to the point about math. Instead of storing an age we could store a COARSE Date of Birth. Where we assign people born in the first three months to January 1, the second three months to April 1, etc.

Calculating fractional age is also a kind of weird thing to think about. Do
we want it to be the number of days alive divided by 365.256, rounded to
the nearest tenth. That doesn't always line up with the typical
understanding of age as the number of birthdays have seen. It's no big
problem, though.

-Forest

On Thu, Dec 6, 2012 at 11:38 AM, David Eads notifications@github.comwrote:

> That seems equivalent to fractional, but now you can't do math on it....
> 
> On Thu, Dec 6, 2012 at 11:27 AM, Forest Gregg notifications@github.comwrote:
> 
> > How about AGE, and then winter, spring, summer, fall
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/pull/15#issuecomment-11095089>.
> 
> ## 
> 
> David Eads - 773.354.2285
> News applications developer, Chicago Tribune (
> http://www.chicagotribune.com/news/data/)
> Founder, FreeGeek Chicago (http://freegeekchicago.org)
> 
> “The awful thing about life is this: everyone has their reasons.” -- Jean
> Renoir
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/pull/15#issuecomment-11095553.

## 

773.888.2718
2231 N. Monticello Ave
Chicago, IL 60647

**Comment by codersquid** [comment]
If we don't need it yet, we can just go with age. What's the worst that could happen? We don't same some amount of data over a long period of time that someone would have to go dig up from records with cook county that may  or may not be available. It would definitely suck for that person, and maybe cost someone a lot of time and/or money; but it wouldn't be catastrophic. not many puppies would die. perhaps 0. meanwhile, we get things done, have a tool that covers most use cases, and we learn (I do) and teach (you do) a lot along the way.

I don't want to overthink it, but I didn't want to underthink it and not learn from you guys.

**Comment by eads** [comment]
+1 to all of this. We should just roll with a calculated age. My concerns
were more about pre-processing data prematurely. There's a handy snippet
for this calculation here:
http://stackoverflow.com/questions/2217488/age-from-birthdate-in-python

**Comment by Davy-jones-Giant-squid** [comment]
I agree that just the age is good enough for data purposes: it gives a year of birth estimation that should be sufficient enough for data mining (I take for example Stephen Levitt in his research about a correlation between a lower criminality rate 20 years after Roe vs Wade). The only reason I can think of for more precise data concerning birth dates would be for predicting personalities based on parents' seasonal behavior (which is what astrology tries to do but fails miserably) but we don't need that, do we?

**Pull request merged**
