### PR TITLE
Spiffy refactoring of utils.py to complement the recent refactor by @nwinklareth 

### PR DESCRIPTION
**Pull request by bepetersn**
- Reduced all the line lengths in utils.py to underneath around 76 characters, as per PEP8.
- Re-ordered the functions in utils.py closer to the order they're used.
- Also separated the new InmateDetails class--plus, importantly all of the logic for actually fetching URLs, into its own file, inmate_details.py

### CODE REVIEW

**Comment by eads** [comment]
Woo woo!

**Comment by bepetersn** [comment]
Had to fix an import bug.

**Comment by bepetersn** [comment]
In utils.py:

"from datetime import datetime[, date]"

The part in brackets is missing from this. Not sure how to edit the pull request files.

**Comment by bepetersn** [comment]
I think I'll sit on this until I figure out how to structure this change better.

**Pull request closed without merging**
