### PR TITLE
DB password

### LINKED ISSUE #386: Database password on config
Why is our database password in the config file? We should use an environment variable.

### PR DESCRIPTION
**Pull request by wilbertom**
This commit forces a change in the database password and moves it to the environment. closes #386

### CODE REVIEW

**Comment by wilbertom** [comment]
Ups, looks like some api code made it there too. Darn it.

**Comment by bepetersn** [comment]
You made an interesting function to prompt people to set env bars, but not
the important work of setting them in any of our admin files, like
scraper.sh, so this will make the scraper fail.

**Comment by wilbertom** [comment]
Yup, I have no idea where I gotta tweak those env variables. I'll add it in a few minutes.

**Comment by bepetersn** [comment]
I'm still setting up my system, or I'd do it.

**Comment by bepetersn** [comment]
hmmmmmmmm, well I messed up that pull request; @wilbertom, can you re-do it?

**Comment by wilbertom** [comment]
Hey Brian, no problem, I still needed to add it to the server's env.

**Comment by wilbertom** [comment]
Wait how did the password get to the deployed app the first time? I don't see any code to tweak. Did someone just ssh and created the database? Or was the database created through an admin interface? If so then it might be easier to use one of those methods again.

```
~/Programming/SC3/cookcountyjail (db-password) wil$ git grep 'walblgadb;lgall'
ccj/config.py:    if db_config['pw'] == 'walblgadb;lgall':

~/Programming/SC3/cookcountyjail (db-password) wil$ git grep cookcountyjail_v2.0_dev
ccj/config.py:        'db_name': env_var('CCJ_DBNAME', 'cookcountyjail_v2_0_dev'),
tests/test_pgsql_installation.py:    result = local('psql cookcountyjail_v2_0_dev -c "\dt"', capture=True)
tests/test_pgsql_installation.py:    local('psql cookcountyjail_v2_0_dev -c "DROP TABLE elaborate_test;"', capture=True)
```

**Comment by bepetersn** [comment]
Well, we should try and handle this the right way.

**Pull request closed without merging**
